version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/var/www

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www

  db:
    build: ./infra/mysql
    volumes:
      - ./infra/mysql/initdb:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "3306:3306"
    environment: #環境変数の追加
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}

  # phpmyadminの設定が書きに記載します。
  phpmyadmin:
    #コンテナ名を決めています。
    container_name: phpmyadmin
    #DockerHubからphpmyadminのイメージを引っ張ってくる設定です。
    image: phpmyadmin/phpmyadmin
    #phpmyadminの環境変数の設定です。MySQLの設定を参照して記載してください。PMA_HOSTSにはservicesのdbを指定しています。
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=${DB_HOST}
      # - PMA_USER=${DB_USERNAME}
      # - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 3000:80
    depends_on:
      - db
  echo-server:
    image: broadcast-echo-server
    build: ./infra/echo-server
    ports:
    - "6001:6001"
    command: laravel-echo-server start
    volumes:
    - ./backend:/work
    working_dir: /work
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - "./infra/redis/data:/data"

volumes:
  db-store: