version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      # - ./src:/data
      - ./src:/var/www

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      # - ./src:/data
      - ./src:/var/www
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # working_dir: /data
    working_dir: /var/www

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: